name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js (needed for GitHub Pages actions)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Recommended Node.js version

    # Build and deploy
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Publish the root directory (contains index.html)
